# Generated by Django 2.2.19 on 2021-11-13 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_categories_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={'ordering': ('raiting',), 'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
    ]
