# Generated by Django 2.2.19 on 2021-11-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20211113_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='creations',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
