# Generated by Django 2.2.19 on 2021-11-18 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_creations_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='raiting',
        ),
    ]
