# Generated by Django 2.2.19 on 2021-11-19 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20211118_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='raiting',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
