# Generated by Django 2.2.19 on 2021-11-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20211119_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creations',
            name='genre',
            field=models.ManyToManyField(null=True, through='reviews.CreationsGenres', to='reviews.Genres'),
        ),
    ]
