# Generated by Django 2.2.19 on 2021-11-20 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20211120_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creations',
            name='genre',
        ),
        migrations.AlterField(
            model_name='creations',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
