# Generated by Django 2.2.19 on 2021-11-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20211120_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='raiting',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
