# Generated by Django 2.2.19 on 2021-11-22 15:32

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_auto_20211120_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='reviews',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='reviews_rev_search__ea5c48_gin'),
        ),
    ]
