# Generated by Django 2.2.19 on 2021-11-22 17:27
# tsvector_update_trigger inert or update
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_auto_20211122_1532'),
    ]

    operations = [
    ]
