# Generated by Django 2.2.19 on 2021-11-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_create_trigger'),
    ]

    operations = [
    ]
