# Generated by Django 2.2.19 on 2021-11-24 18:17

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_create_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
