# Generated by Django 2.2.19 on 2021-11-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_auto_20211124_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={'ordering': ('author',), 'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.RenameField(
            model_name='authors',
            old_name='raiting',
            new_name='number_of_rating',
        ),
        migrations.AddField(
            model_name='authors',
            name='sum_of_rating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
