# Generated by Django 2.2.19 on 2021-12-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_auto_20211130_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='rating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
