# Generated by Django 2.2.19 on 2021-12-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0018_authors_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='rating',
            field=models.FloatField(default=0, null=True),
        ),
    ]
