# Generated by Django 2.2.19 on 2021-12-03 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0020_pictures'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pictures',
            options={'verbose_name': 'Picture', 'verbose_name_plural': 'Pictures'},
        ),
    ]
