# Generated by Django 2.2.19 on 2021-12-04 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0021_auto_20211203_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picture', to='reviews.Reviews'),
        ),
    ]
