# Generated by Django 2.2.19 on 2021-12-04 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0022_pictures_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='review',
        ),
        migrations.CreateModel(
            name='ReviewPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Pictures')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Reviews')),
            ],
        ),
        migrations.AddField(
            model_name='reviews',
            name='pictures',
            field=models.ManyToManyField(blank=True, null=True, through='reviews.ReviewPicture', to='reviews.Pictures'),
        ),
    ]
