# Generated by Django 2.2.19 on 2021-12-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0023_auto_20211204_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='pictures',
            field=models.ManyToManyField(null=True, through='reviews.ReviewPicture', to='reviews.Pictures'),
        ),
    ]
