# Generated by Django 2.2.19 on 2021-12-04 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0024_auto_20211204_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewpicture',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='reviews.Reviews'),
        ),
    ]
