# Generated by Django 2.2.19 on 2021-12-04 12:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0025_auto_20211204_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='pictures',
        ),
        migrations.AddField(
            model_name='reviews',
            name='image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
