# Generated by Django 2.2.19 on 2021-12-04 19:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0026_auto_20211204_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
