# Generated by Django 2.2.19 on 2021-11-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_create_trigger'),
    ]

    operations = [
        migrations.RunSQL(
                sql='''
    CREATE TRIGGER review_update_trigger
    BEFORE INSERT OR UPDATE OF text, name, search_vector
    ON reviews_reviews
    FOR EACH ROW EXECUTE PROCEDURE
    tsvector_update_trigger(search_vector, 'pg_catalog.russian', text, name);
    UPDATE reviews_reviews SET search_vector = NULL;
    ''',
        reverse_sql='''
        DROP TRIGGER IF EXISTS review_update_trigger
        on reviews_reviews;
        '''
            )
    ]
